server:
  port: 8081
  servlet:
    context-path: /${ro.marius.cirstea.properties.app-name}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${ro.marius.cirstea.properties.app-name}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: changeit
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: detect
  application:
    name: ${ro.marius.cirstea.properties.app-name}
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: @environment@

logging.level.root: INFO

ro:
  marius:
    cirstea:
      properties:
        jwtExpiration: 3600000
        jwtRefreshExpiration: 28800000
        app-name: @app.name@